<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE BodgalAttila_orarend [
    <!ELEMENT BodgalAttila_orarend (ora+)>

        <!ELEMENT ora (targy,idopont,helyszin,oktato,szak)>
            <!ATTLIST ora id ID #REQUIRED>
            <!ATTLIST ora tipus (Gyakorlat|Elmélet) "Elmélet">

            <!ELEMENT targy (#PCDATA)>
            <!ELEMENT idopont (nap,tol,ig)>
                <!ELEMENT nap (#PCDATA)>
                <!ELEMENT tol (#PCDATA)>
                <!ELEMENT ig (#PCDATA)>
            <!ELEMENT helyszin (#PCDATA)>
            <!ELEMENT oktato (#PCDATA)>
            <!ELEMENT szak (#PCDATA)>
]>

<BodgalAttila_orarend>
    <ora id="id_01" tipus="Gyakorlat">
        <targy>Integrált_vállalati_rendszerek</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>0800</tol>
            <ig>1000</ig>
        </idopont>
        <helyszin>Inf_203</helyszin>
        <oktato>dr._Kulcsárné_Dr._Forrai_Mónika</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_02" tipus="Elmélet">
        <targy>Adatkezelés_XML_ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1000</tol>
            <ig>1200</ig>
        </idopont>
        <helyszin >Inf_103</helyszin>
        <oktato>Dr._Bednarik_László</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_03" tipus="Gyakorlat">
        <targy>Adatkezelés_XML_ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1200</tol>
            <ig>1400</ig>
        </idopont>
        <helyszin>Inf_103</helyszin>
        <oktato>Dr._Bednarik_László</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_04" tipus="Elmélet">
        <targy>Integrált_vállalati_rendszerek</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1400</tol>
            <ig>1600</ig>
        </idopont>
        <helyszin>A1_227</helyszin>
        <oktato>Dr._Dadvandipour_Samad</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_05" tipus="Elmélet">
        <targy>Web-es_alkalmazások_C#</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1400</tol>
            <ig>1600</ig>
        </idopont>
        <helyszin>Inf_101</helyszin>
        <oktato>Árvai_László_Lajos</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_06" tipus="Gyakorlat">
        <targy>Web-es_alkalmazások_C#</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>1600</tol>
            <ig>1800</ig>
        </idopont>
        <helyszin>Inf_101</helyszin>
        <oktato>Dr._Mileff_Péter</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_07" tipus="Gyakorlat">
        <targy>Mesterséges_intelligencia_alapok</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>1000</tol>
            <ig>1200</ig>
        </idopont>
        <helyszin>X_előadó</helyszin>
        <oktato>Fazekas_Levente_Áron</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
    <ora id="id_08" tipus="Elmélet">
        <targy>Mesterséges_intelligencia_alapok</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>1600</tol>
            <ig>1800</ig>
        </idopont>
        <helyszin>XXXII_előadó</helyszin>
        <oktato>Kunné_Dr._Tamás_Judit</oktato>
        <szak>Mérnökinfó</szak>
    </ora>
</BodgalAttila_orarend>